package com.evalorithm.ui.student

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.BaseExpandableAdapter
import android.widget.Toast
import androidx.activity.viewModels
import androidx.appcompat.app.AlertDialog
import androidx.appcompat.app.AppCompatActivity
import androidx.lifecycle.lifecycleScope
import androidx.recyclerview.widget.LinearLayoutManager
import com.evalorithm.data.local.TokenManager
import com.evalorithm.databinding.ActivityStudentHelpBinding
import com.evalorithm.databinding.ItemFaqBinding
import com.evalorithm.util.Resource
import com.evalorithm.viewmodel.OBEViewModel
import dagger.hilt.android.AndroidEntryPoint
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch
import javax.inject.Inject

@AndroidEntryPoint
class StudentHelpActivity : AppCompatActivity() {

    private lateinit var binding: ActivityStudentHelpBinding
    private val viewModel: OBEViewModel by viewModels()

    @Inject
    lateinit var tokenManager: TokenManager

    private val faqQuestions = listOf(
        "How do I take an exam?" to "Navigate to My Exams from the sidebar, select an active exam, and click Start. You will be given the specified duration to complete all questions.",
        "How do I view my results?" to "After submitting an exam, results are shown immediately. You can also view past results from the My Exams section.",
        "How do I check my analytics?" to "Go to My Analytics from the sidebar to view your performance charts, accuracy trends, and subject-wise breakdowns.",
        "What is Adaptive Testing?" to "Adaptive Testing adjusts question difficulty based on your performance in real-time, providing a personalized assessment experience.",
        "How do I contact admin?" to "Use the Contact Admin form below to create a support ticket. The admin team will respond promptly.",
        "How are certificates generated?" to "Certificates are generated by the admin after you complete an exam and meet the required criteria. Check the My Certificates section."
    )

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityStudentHelpBinding.inflate(layoutInflater)
        setContentView(binding.root)

        setupToolbar()
        setupFAQ()
        setupContactForm()
        loadTickets()
        observeTickets()
    }

    private fun setupToolbar() {
        setSupportActionBar(binding.toolbar)
        supportActionBar?.setDisplayHomeAsUpEnabled(true)
        supportActionBar?.title = "Help & Support"
        binding.toolbar.setNavigationOnClickListener { onBackPressedDispatcher.onBackPressed() }
    }

    private fun setupFAQ() {
        binding.tvNoFaq.visibility = View.GONE
        val adapter = FAQAdapter(faqQuestions)
        // Use a simple LinearLayout approach for FAQs
        binding.faqContainer.removeAllViews()
        faqQuestions.forEach { (question, answer) ->
            val faqBinding = ItemFaqBinding.inflate(layoutInflater, binding.faqContainer, false)
            faqBinding.tvQuestion.text = question
            faqBinding.tvAnswer.text = answer
            faqBinding.root.setOnClickListener {
                if (faqBinding.tvAnswer.visibility == View.VISIBLE) {
                    faqBinding.tvAnswer.visibility = View.GONE
                } else {
                    faqBinding.tvAnswer.visibility = View.VISIBLE
                }
            }
            binding.faqContainer.addView(faqBinding.root)
        }
    }

    private fun setupContactForm() {
        binding.btnCreateTicket.setOnClickListener {
            val subject = binding.etSubject.text.toString().trim()
            val description = binding.etDescription.text.toString().trim()

            if (subject.isEmpty() || description.isEmpty()) {
                Toast.makeText(this, "Please fill all fields", Toast.LENGTH_SHORT).show()
                return@setOnClickListener
            }

            viewModel.createTicket(subject, description)
            Toast.makeText(this, "Support ticket created", Toast.LENGTH_SHORT).show()
            binding.etSubject.text?.clear()
            binding.etDescription.text?.clear()
        }
    }

    private fun loadTickets() {
        lifecycleScope.launch {
            val userId = tokenManager.getUserId().first()
            viewModel.loadTickets(userId)
        }
    }

    private fun observeTickets() {
        viewModel.tickets.observe(this) { resource ->
            when (resource) {
                is Resource.Success -> {
                    val tickets = resource.data ?: emptyList()
                    if (tickets.isNotEmpty()) {
                        val ticketTexts = tickets.joinToString("\n\n") { ticket ->
                            "Subject: ${ticket.subject}\nStatus: ${ticket.status}\nCreated: ${ticket.createdAt}"
                        }
                        AlertDialog.Builder(this)
                            .setTitle("Your Support Tickets")
                            .setMessage(ticketTexts)
                            .setPositiveButton("OK", null)
                            .show()
                    }
                }
                is Resource.Error -> {
                    Toast.makeText(this, resource.message, Toast.LENGTH_SHORT).show()
                }
                else -> {}
            }
        }
    }

    private inner class FAQAdapter(private val items: List<Pair<String, String>>) : BaseExpandableAdapter() {
        override fun getGroupCount() = items.size
        override fun getChildrenCount(groupPosition: Int) = 1
        override fun getGroup(groupPosition: Int) = items[groupPosition].first
        override fun getChild(groupPosition: Int, childPosition: Int) = items[groupPosition].second
        override fun getGroupId(groupPosition: Int) = groupPosition.toLong()
        override fun getChildId(groupPosition: Int, childPosition: Int) = childPosition.toLong()
        override fun hasStableIds() = false
        override fun isChildSelectable(groupPosition: Int, childPosition: Int) = true
        override fun getGroupView(groupPosition: Int, isExpanded: Boolean, convertView: View?, parent: ViewGroup?): View = View(this@StudentHelpActivity)
        override fun getChildView(groupPosition: Int, childPosition: Int, isLastChild: Boolean, convertView: View?, parent: ViewGroup?): View = View(this@StudentHelpActivity)
    }
}
